In [1]:
import numpy as np

In [2]:
z=np.array([10,20.5,"Hello"])     # creating 1D array
z

array(['10', '20.5', 'Hello'], dtype='<U32')

In [50]:
print(z)

['10' '20.5' 'Hello']


In [51]:
array1=np.array([10,20.5,50])     # creating 1D array
array1

array([10. , 20.5, 50. ])

In [52]:
print(array1)                  #printing 1D array

[10.  20.5 50. ]


In [56]:
print(array1[0] + array1[2])      #summing 2 elements of 1D array

60.0


In [57]:
array2 = np.array([[1, 2, 3], [4, 5, 6]])       # creating 2D array
print(array2)

[[1 2 3]
 [4 5 6]]


In [58]:
print(array2[0][2], array2[1][1])              # accessing two different index elements of 2D array

3 5


In [59]:
print(array2[0][2]+ array2[1][1])            # summing to different index element of 2D array

8


# Converting List into Numpy Array

In [61]:
x=[]
n=int(input("Enter Length of an Array : "))
for i in range(n):
    i=int(input(" Enter value of index: "))
    x.append(i)
ar=np.array(x)
print(ar)

Enter Length of an Array : 2
 Enter value of index: 100
 Enter value of index: 500
[100 500]


# Calculating Sum in Numpy Arrays

In [62]:
sum=0
sum=np.sum(ar)
sum

600

## Slicing in Array

In [34]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [35]:
print("Slicing from 0-2 index" , arr[0:3])

Slicing from 0-2 index [1 2 3]


In [36]:
print("Slicing from 4 to end index" , arr[4:])

Slicing from 4 to end index [ 5  6  7  8  9 10]


In [37]:
print("\n Slicing from 0 to 5 index" , arr[:4])


 Slicing from 0 to 5 index [1 2 3 4]


In [38]:
print("\n Slicing from right side index to the total length" , arr[:-4])


 Slicing from right side index to the total length [1 2 3 4 5 6]


In [39]:
print("\n Slicing from right side index to fix length" , arr[-4:-2]) # [-2:-4] will give empty array why? just think


 Slicing from right side index to fix length [7 8]


In [40]:
print("\n Print every second element in array" , arr[::2])


 Print every second element in array [1 3 5 7 9]


In [41]:
print("\n Print every other element in array" , arr[1:7:2])


 Print every other element in array [2 4 6]


In [42]:
print(arr.dtype)                   #checking DataType of an Array

int32


In [43]:
arr_f= np.array([1.1, 2.1, 3.1])          #typecasting of arrays

newarr = arr_f.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [44]:
for i in arr:
    print (i)

1
2
3
4
5
6
7
8
9
10


In [45]:
x=np.array_split(arr,4)
print(x)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]


In [46]:
print(x[0])
print(x[1])
print(x[2])

[1 2 3]
[4 5 6]
[7 8]
